### ISSUE TITLE
"showOnlyOn" not working

### ISSUE THREAD

**Issue by cyber152** [mumblebaj/MMM-PhilipsHue#1]
hi @mumblebaj 

I'm having a problem with the "show only lights on" feature that doesn't work at home.
my configuration displays well the hue bridge, the lights go up well on the mirror but whether I put "showOnlyOn" on true or false the lights "not on" always remain displayed
 can you help me please ?

thank you 

> {		    module: 'MMM-PhilipsHue',
> 		    position: 'top_right',
> 		    header: 'Eclairage Philips Hue',
> 		    config: {
> 			bridgeip: "192.168.1.23", //Your Bridge IP
> 			userid: "4xxBbCJ-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxYqGn927v",
> 			colour: true, //If set to true the module shows only the lights which are on
> 			showOnlyOn: true
> 		    	}
> 		}

preview : 

[<a href="https://ibb.co/nwwS15X"><img src="https://i.ibb.co/nwwS15X/A06-F6-C5-A-65-DA-4-B02-B341-AE494-E5-F5-B1-F.jpg" alt="A06-F6-C5-A-65-DA-4-B02-B341-AE494-E5-F5-B1-F" border="0"></a>](url)

**Comment by mumblebaj** [comment]
Hi. Sorry for the late reply. I will have a look and come back to you.

**Comment by mumblebaj** [comment]
Hi. I have made a change and it should now work for option lights.

Your config need to resemble something like the below.

```
                {
                    module: 'MMM-PhilipsHue',
                    disabled: false,
                    position: 'bottom_right',
                    config:{
                        bridgeip: "xxx.xxx.0.xxx",
                        userid: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                        updateInterval: 10000 * 5,
                        **lightsOrGroups: "lights",**
                        **showOnlyOn: true,**
                        showLabel: true,
                        colour: true
                        }
                },
```
Let me know if that resolves your issue.

**Comment by cyber152** [comment]
Hi, it works very well now. 
I have that the "lights on" that are displayed, good job for this MMM-module and thank you again for the speed of your intervention

I deleted the directory and did a new installation of the module, modified the code as you told me and it works :+1:

<a href="https://ibb.co/hB9Kjwn"><img src="https://i.ibb.co/hB9Kjwn/unnamed2.jpg" alt="unnamed2" border="0"></a>

**Comment by mumblebaj** [comment]
You should have just done a git pull in the module folder. Didn't have to delete the folder. Glad it is resolved for you.
