### ISSUE TITLE
Different icons for different rooms

### ISSUE THREAD

**Issue by kurtern84** [mumblebaj/MMM-PhilipsHue#2]
Hi.

I have added the philips hue icons and I wonder if it is possible to set different light icon for different rooms?

**Comment by mumblebaj** [comment]
Hi. Sorry, but unfortunately this is not supported in the module. Would be too difficult to match icons to different rooms. I have seen somebody with about 50 lights. If you want to use a specific icon for all the lights I can make that a variable that you can provide in the config which then sets the icon for all the lights.  But to assign different icons to different lights would just be impossible to achieve.

**Comment by kurtern84** [comment]
I undetstand! No need for that, i have updated the icons already:) but thanks anyway.
